train: ../data/actions/train/images
val: ../data/actions/valid/images
test: ../data/actions/test/images

nc: 5
names: ['block', 'defense', 'serve', 'set', 'spike']

training_params:
  weights: yolo12s.pt
  project: runs/actions
  name: yolo12s-actions
  epochs: 100
  batch: 16
  imgsz: 640
  device: 0
  workers: 8
  patience: 20
  seed: 42
  optimizer: adam
  lr0: 0.001
  resume: false
  exist_ok: false

roboflow:
  workspace: current-sb7yp
  project: volly-vision
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/current-sb7yp/volly-vision/dataset/1
