train: ../data/ball/train/images
val: ../data/ball/valid/images
test: ../data/ball/test/images

nc: 1
names: ['ball']

training_params:
  weights: yolo12s.pt
  project: runs/ball
  name: yolo12s-ball
  epochs: 100
  batch: 16
  imgsz: 640
  device: 0
  workers: 8
  patience: 20
  seed: 42
  optimizer: adam
  lr0: 0.001
  run_test: true
  resume: false
  exist_ok: false


roboflow:
  workspace: primaryws
  project: volleyball_ball_object_detection_dataset
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/primaryws/volleyball_ball_object_detection_dataset/dataset/1